export enum Action {
    IN_PROGRESS = 'IN_PROGRESS',
    ENQUEUED = 'ENQUEUED',
    SUCCESS = 'SUCCESS',
    ERROR = 'ERROR',
    RETRY = 'RETRY',
    MOVED_TO_DLQ = 'MOVED_TO_DLQ',
    ENQUEUED_IMMEDIATE = 'ENQUEUED_IMMEDIATE'
}