import { MigrationInterface, QueryRunner } from "typeorm";

export class $npmConfigName1770286722113 implements MigrationInterface {
    name = ' $npmConfigName1770286722113'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`firstName\` varchar(150) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`lastName\` varchar(150) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` CHANGE \`expiresAt\` \`expiresAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP COLUMN \`context\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD \`context\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`policy_rules\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`policy_rules\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`policy_rules\` CHANGE \`ruleType\` \`ruleType\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`policies\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`policies\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`policies\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`policies\` ADD \`metadata\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`policies\` DROP COLUMN \`conditions\``);
        await queryRunner.query(`ALTER TABLE \`policies\` ADD \`conditions\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`policy_permissions\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`policy_permissions\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`policy_permissions\` DROP COLUMN \`conditions\``);
        await queryRunner.query(`ALTER TABLE \`policy_permissions\` ADD \`conditions\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`permissions\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`permissions\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`permissions\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP COLUMN \`constraints\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD \`constraints\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`metadata\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`applications\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`applications\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`applications\` CHANGE \`apiSecret\` \`apiSecret\` varchar(512) NULL`);
        await queryRunner.query(`ALTER TABLE \`applications\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`applications\` DROP COLUMN \`settings\``);
        await queryRunner.query(`ALTER TABLE \`applications\` ADD \`settings\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`user_applications\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_applications\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_applications\` CHANGE \`membershipExpiresAt\` \`membershipExpiresAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`user_applications\` DROP COLUMN \`attributes\``);
        await queryRunner.query(`ALTER TABLE \`user_applications\` ADD \`attributes\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`sessions\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`sessions\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`sessions\` CHANGE \`userAgent\` \`userAgent\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`sessions\` CHANGE \`ipAddress\` \`ipAddress\` varchar(45) NULL`);
        await queryRunner.query(`ALTER TABLE \`sessions\` CHANGE \`revokedAt\` \`revokedAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`passwordHash\` \`passwordHash\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone\` \`phone\` varchar(20) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`profile\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`profile\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`lastLoginAt\` \`lastLoginAt\` timestamp NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_13c69424c440a0e765053feb4b\` ON \`audit_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_5ee52ff271c0f9bca5f97daa0a\` ON \`audit_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_76c65856903601a6fa723a45a2\` ON \`audit_logs\``);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`entityType\` \`entityType\` enum ('USER', 'APPLICATION', 'ROLE', 'PERMISSION', 'POLICY', 'POLICY_RULE', 'USER_APPLICATION', 'USER_ROLE', 'ROLE_PERMISSION', 'POLICY_PERMISSION', 'ACCESS_REQUEST') NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`entityId\` \`entityId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`permition\` \`permition\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`userId\` \`userId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`userEmail\` \`userEmail\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`applicationId\` \`applicationId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`applicationName\` \`applicationName\` varchar(120) NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` DROP COLUMN \`details\``);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` ADD \`details\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`ipAddress\` \`ipAddress\` varchar(45) NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`userAgent\` \`userAgent\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`endpoint\` \`endpoint\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`httpMethod\` \`httpMethod\` varchar(10) NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`statusCode\` \`statusCode\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`processingTime\` \`processingTime\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`correlationId\` \`correlationId\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`abac_users\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`abac_users\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`abac_users\` CHANGE \`department\` \`department\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`abac_users\` CHANGE \`role\` \`role\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`abac_users\` CHANGE \`attributes\` \`attributes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`user_policy_assignments\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_policy_assignments\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_policy_assignments\` DROP COLUMN \`conditions\``);
        await queryRunner.query(`ALTER TABLE \`user_policy_assignments\` ADD \`conditions\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`user_policy_assignments\` CHANGE \`expiresAt\` \`expiresAt\` timestamp NULL`);
        await queryRunner.query(`CREATE INDEX \`IDX_76c65856903601a6fa723a45a2\` ON \`audit_logs\` (\`applicationId\`, \`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_5ee52ff271c0f9bca5f97daa0a\` ON \`audit_logs\` (\`userId\`, \`action\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_13c69424c440a0e765053feb4b\` ON \`audit_logs\` (\`entityType\`, \`entityId\`)`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`IDX_13c69424c440a0e765053feb4b\` ON \`audit_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_5ee52ff271c0f9bca5f97daa0a\` ON \`audit_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_76c65856903601a6fa723a45a2\` ON \`audit_logs\``);
        await queryRunner.query(`ALTER TABLE \`user_policy_assignments\` CHANGE \`expiresAt\` \`expiresAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_policy_assignments\` DROP COLUMN \`conditions\``);
        await queryRunner.query(`ALTER TABLE \`user_policy_assignments\` ADD \`conditions\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_policy_assignments\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_policy_assignments\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`abac_users\` CHANGE \`attributes\` \`attributes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`abac_users\` CHANGE \`role\` \`role\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`abac_users\` CHANGE \`department\` \`department\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`abac_users\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`abac_users\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`correlationId\` \`correlationId\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`processingTime\` \`processingTime\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`statusCode\` \`statusCode\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`httpMethod\` \`httpMethod\` varchar(10) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`endpoint\` \`endpoint\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`userAgent\` \`userAgent\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`ipAddress\` \`ipAddress\` varchar(45) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` DROP COLUMN \`details\``);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` ADD \`details\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`applicationName\` \`applicationName\` varchar(120) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`applicationId\` \`applicationId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`userEmail\` \`userEmail\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`userId\` \`userId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`permition\` \`permition\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`entityId\` \`entityId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`entityType\` \`entityType\` enum ('USER', 'APPLICATION', 'ROLE', 'PERMISSION', 'POLICY', 'POLICY_RULE', 'USER_APPLICATION', 'USER_ROLE', 'ROLE_PERMISSION', 'POLICY_PERMISSION', 'ACCESS_REQUEST') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE INDEX \`IDX_76c65856903601a6fa723a45a2\` ON \`audit_logs\` (\`applicationId\`, \`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_5ee52ff271c0f9bca5f97daa0a\` ON \`audit_logs\` (\`userId\`, \`action\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_13c69424c440a0e765053feb4b\` ON \`audit_logs\` (\`entityType\`, \`entityId\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`lastLoginAt\` \`lastLoginAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`profile\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`profile\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone\` \`phone\` varchar(20) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`passwordHash\` \`passwordHash\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sessions\` CHANGE \`revokedAt\` \`revokedAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sessions\` CHANGE \`ipAddress\` \`ipAddress\` varchar(45) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sessions\` CHANGE \`userAgent\` \`userAgent\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sessions\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sessions\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_applications\` DROP COLUMN \`attributes\``);
        await queryRunner.query(`ALTER TABLE \`user_applications\` ADD \`attributes\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_applications\` CHANGE \`membershipExpiresAt\` \`membershipExpiresAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_applications\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_applications\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`applications\` DROP COLUMN \`settings\``);
        await queryRunner.query(`ALTER TABLE \`applications\` ADD \`settings\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`applications\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`applications\` CHANGE \`apiSecret\` \`apiSecret\` varchar(512) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`applications\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`applications\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`metadata\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP COLUMN \`constraints\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD \`constraints\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`permissions\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`permissions\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`permissions\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`policy_permissions\` DROP COLUMN \`conditions\``);
        await queryRunner.query(`ALTER TABLE \`policy_permissions\` ADD \`conditions\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`policy_permissions\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`policy_permissions\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`policies\` DROP COLUMN \`conditions\``);
        await queryRunner.query(`ALTER TABLE \`policies\` ADD \`conditions\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`policies\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`policies\` ADD \`metadata\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`policies\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`policies\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`policy_rules\` CHANGE \`ruleType\` \`ruleType\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`policy_rules\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`policy_rules\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP COLUMN \`context\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD \`context\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` CHANGE \`expiresAt\` \`expiresAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` CHANGE \`updatedBy\` \`updatedBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`lastName\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`firstName\``);
    }

}
